# Generated by Django 4.0.5 on 2022-06-08 06:55

from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'username already taken'}, max_length=120, unique=True, validators=[users.validators.UsernameValidator()])),
                ('web_token', models.CharField(max_length=255)),
                ('mob_token', models.CharField(max_length=255)),
                ('is_mob_logged', models.BooleanField(default=False)),
                ('is_web_logged', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='roles.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
