# Generated by Django 4.0.5 on 2022-06-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
